[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
bsc = "${BSC_RPC}"
polygon = "https://polygon-mainnet.infura.io/v3/${INFURA_KEY}"
avalanche = "https://avalanche-mainnet.infura.io/v3/${INFURA_KEY}"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}"
optimism = "https://optimism-mainnet.infura.io/v3/${INFURA_KEY}"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
